insert into public.jugadores (nombre, apellido, posicion, "equipoActual") values
  ('Franco', 'Aguilar', 'Pilar Izquierdo', 'Regatas'),
  ('Julián', 'Aguilar', 'Centro', 'Regatas'),
  ('Martín', 'Aguilar', 'Centro', 'Regatas'),
  ('Felix', 'Arnedo', 'Centro', 'Regatas'),
  ('Santiago', 'Alberro', 'Pilar Derecho', 'Regatas'),
  ('Tomas', 'Barbaccia', 'Pilar Izquierdo', 'Regatas'),
  ('Bautista', 'Barla', 'Centro', 'Regatas'),
  ('Cruz', 'Barla', 'Apertura', 'Regatas'),
  ('José', 'Basombrio', 'Segunda Línea', 'Regatas'),
  ('Santiago', 'Basombrio', 'Ala', 'Regatas'),
  ('Segundo', 'Bazzini', 'Medio Scrum', 'Regatas'),
  ('Santiago', 'Bleif', 'Segunda Línea', 'Regatas'),
  ('Tomas', 'Bodini', 'Segunda Línea', 'Regatas'),
  ('Francisco', 'Bodini', 'Hooker', 'Regatas'),
  ('Francisco', 'Bourse', 'Hooker', 'Regatas'),
  ('Thiago', 'Bourse', 'Pilar Izquierdo', 'Regatas'),
  ('Valentin', 'Bourse', 'Ala', 'Regatas'),
  ('Juan', 'Brizuela', 'Pilar Izquierdo', 'Regatas'),
  ('Joaquín', 'Burgos Calvente', 'Octavo', 'Regatas'),
  ('Facundo', 'Calderotto', 'Hooker', 'Regatas'),
  ('Estanislao', 'Calvente', 'Hooker', 'Regatas'),
  ('Enrique', 'Camerlinckx', 'Wing', 'Regatas'),
  ('Felipe', 'Camerlinckx', 'Octavo', 'Regatas'),
  ('Juan Francisco', 'Camerlinckx', 'Apertura', 'Regatas'),
  ('Justo', 'Camerlinckx', 'Fullback', 'Regatas'),
  ('Mateo', 'Camerlinckx', 'Centro', 'Regatas'),
  ('Serafin', 'Campos', 'Wing', 'Regatas'),
  ('Lucas', 'Cariaga', 'Pilar Izquierdo', 'Regatas'),
  ('Santino', 'Cariaga', 'Pilar Derecho', 'Regatas'),
  ('Pablo', 'Carpi', 'Segunda Línea', 'Regatas'),
  ('Federico', 'Castilla', 'Wing', 'Regatas'),
  ('Fernando', 'Castilla', 'Hooker', 'Regatas'),
  ('Tomás', 'Castro Feijoo', 'Pilar Izquierdo', 'Regatas'),
  ('Felipe', 'Castro Juárez', 'Hooker', 'Regatas'),
  ('Tomás', 'Castro Juárez', 'Segunda Línea', 'Regatas'),
  ('Ignacio', 'Commisso', 'Centro', 'Regatas'),
  ('Pedro', 'Curci', 'Octavo', 'Regatas'),
  ('Estanislao', 'De la torre', 'Ala', 'Regatas'),
  ('Felipe', 'De la torre', 'Ala', 'Regatas'),
  ('Francisco Pío María', 'de la Torre', 'Ala', 'Regatas'),
  ('José', 'de la Torre', 'Apertura', 'Regatas'),
  ('Manuel', 'De la torre', 'Medio Scrum', 'Regatas'),
  ('Esteban', 'De la torre', 'Medio Scrum', 'Regatas'),
  ('Manuel', 'de los Reyes', 'Hooker', 'Regatas'),
  ('Mateo', 'Debernardi', 'Ala', 'Regatas'),
  ('Caetano', 'Derudi', 'Wing', 'Regatas'),
  ('Agustin', 'Dubini', 'Segunda Línea', 'Regatas'),
  ('Francisco', 'Esposito', 'Pilar Izquierdo', 'Regatas'),
  ('Facundo', 'Estrada', 'Apertura', 'Regatas'),
  ('Pedro', 'Fassi', 'Segunda Línea', 'Regatas'),
  ('Marcos', 'Ferro', 'Ala', 'Regatas'),
  ('Mateo', 'Flynn', 'Ala', 'Regatas'),
  ('Santiago', 'Franzini', 'Ala', 'Regatas'),
  ('Conrado', 'Friedenreich', 'Segunda Línea', 'Regatas'),
  ('Marco', 'Friedenreich', 'Wing', 'Regatas'),
  ('Felipe', 'Galli', 'Pilar Izquierdo', 'Regatas'),
  ('Gonzalo', 'Galli', 'Wing', 'Regatas'),
  ('Agustín', 'García Campos', 'Octavo', 'Regatas'),
  ('Pedro', 'Garcia Colinas', 'Hooker', 'Regatas'),
  ('Julián', 'Garcia Lemos', 'Hooker', 'Regatas'),
  ('Bautista', 'Gatica', 'Wing', 'Regatas'),
  ('Juan Ignacio', 'Gatica', 'Octavo', 'Regatas'),
  ('Agustín', 'Giavedoni', 'Octavo', 'Regatas'),
  ('Tomas', 'Giavedoni', 'Ala', 'Regatas'),
  ('Miguel', 'Gigena', 'Wing', 'Regatas'),
  ('Juan Manuel', 'Gobet', 'Pilar Derecho', 'Regatas'),
  ('Lucas', 'Gobet', 'Ala', 'Regatas'),
  ('Facundo', 'Goischain', 'Pilar Derecho', 'Regatas'),
  ('Jose', 'Gonzalez', 'Segunda Línea', 'Regatas'),
  ('Juan', 'Gonzalez', 'Ala', 'Regatas'),
  ('Ian', 'González', 'Ala', 'Regatas'),
  ('Joaquín', 'González Benegas', 'Centro', 'Regatas'),
  ('Benjamin', 'Guerra', 'Medio Scrum', 'Regatas'),
  ('Felipe', 'Guerreiro', 'Medio Scrum', 'Regatas'),
  ('Benjamín', 'Guerriero', 'Medio Scrum', 'Regatas'),
  ('Joaquín', 'Guerriero', 'Apertura', 'Regatas'),
  ('Juan Cruz', 'Hitta', 'Pilar Derecho', 'Regatas'),
  ('Marcos', 'Joseph', 'Medio Scrum', 'Regatas'),
  ('Tobias', 'Klappenbach', 'Centro', 'Regatas'),
  ('Beltran', 'Landivar', 'Hooker', 'Regatas'),
  ('Mariano', 'Ledesma', 'Fullback', 'Regatas'),
  ('Emiliano', 'Leiva', 'Segunda Línea', 'Regatas'),
  ('Santiago', 'Lencioni', 'Centro', 'Regatas'),
  ('Francisco', 'Limia', 'Centro', 'Regatas'),
  ('Bautista', 'Lopez Mañan', 'Segunda Línea', 'Regatas'),
  ('Manuel', 'Lozano', 'Ala', 'Regatas'),
  ('Ignacio', 'Machera', 'Hooker', 'Regatas'),
  ('Santiago', 'Mackinlay', 'Ala', 'Regatas'),
  ('Bautista', 'Mackinlay', 'Centro', 'Regatas'),
  ('Segundo', 'Maldonado', 'Pilar Izquierdo', 'Regatas'),
  ('Leonardo', 'Martinez', 'Pilar Derecho', 'Regatas'),
  ('Juan Bautista', 'Martínez Barbosa', 'Centro', 'Regatas'),
  ('Jonathan Gabriel', 'Melo', 'Segunda Línea', 'Regatas'),
  ('Martín Segundo', 'Mendez', 'Wing', 'Regatas'),
  ('Timoteo', 'Mendez', 'Wing', 'Regatas'),
  ('Santiago', 'Méndez', 'Segunda Línea', 'Regatas'),
  ('Benjamín', 'Mendez Chavarría', 'Centro', 'Regatas'),
  ('Sixto', 'Mihura', 'Ala', 'Regatas'),
  ('Ramiro', 'Moadeb', 'Centro', 'Regatas'),
  ('Franco', 'Monopoli', 'Pilar Derecho', 'Regatas'),
  ('Marcos', 'Mortstedt', 'Ala', 'Regatas'),
  ('Francisco', 'Muñoz', 'Hooker', 'Regatas'),
  ('Juan', 'Muzzio', 'Segunda Línea', 'Regatas'),
  ('Conrado', 'Nano', 'Centro', 'Regatas'),
  ('Alejandro', 'Notari', 'Segunda Línea', 'Regatas'),
  ('Daniel', 'Nuñez', 'Segunda Línea', 'Regatas'),
  ('Brian', 'Ortiz', 'Pilar Izquierdo', 'Regatas'),
  ('Miguel', 'Pan Peralta', 'Ala', 'Regatas'),
  ('Tomas', 'Parareda', 'Medio Scrum', 'Regatas'),
  ('Marcos', 'Parodi', 'Segunda Línea', 'Regatas'),
  ('Matias', 'Pascuet', 'Ala', 'Regatas'),
  ('Santiago', 'Pastrana', 'Centro', 'Regatas'),
  ('Valentin', 'Pastrana', 'Centro', 'Regatas'),
  ('Ignacio', 'Pereyra', 'Fullback', 'Regatas'),
  ('Facundo', 'Pereyra', 'Centro', 'Regatas'),
  ('Toribio', 'Perez del Cerro', 'Wing', 'Regatas'),
  ('Zenon', 'Perez del Cerro', 'Centro', 'Regatas'),
  ('Blas', 'Piñeyro', 'Centro', 'Regatas'),
  ('Tadeo', 'Piñeyro', 'Centro', 'Regatas'),
  ('Francisco', 'Pisani', 'Centro', 'Regatas'),
  ('Francisco', 'Ploder', 'Segunda Línea', 'Regatas'),
  ('Santino', 'Pomilio', 'Apertura', 'Regatas'),
  ('Martín', 'Prado', 'Wing', 'Regatas'),
  ('Ignacio', 'Racedo', 'Fullback', 'Regatas'),
  ('Felipe', 'Rastelli', 'Centro', 'Regatas'),
  ('Juan Ignacio', 'Rau', 'Segunda Línea', 'Regatas'),
  ('Joaquín', 'Recalde', 'Wing', 'Regatas'),
  ('Santiago', 'Recaré', 'Segunda Línea', 'Regatas'),
  ('Tomas', 'Reznick', 'Wing', 'Regatas'),
  ('Benjamin', 'Richards', 'Medio Scrum', 'Regatas'),
  ('Benjamín', 'Rivarola', 'Wing', 'Regatas'),
  ('Santiago', 'Rodríguez', 'Wing', 'Regatas'),
  ('Francisco', 'Rodriguez Denker', 'Pilar Izquierdo', 'Regatas'),
  ('Tomas', 'Rodriguez Gilligan', 'Apertura', 'Regatas'),
  ('Santiago', 'Roldan', 'Segunda Línea', 'Regatas'),
  ('Marcos', 'Romero Victorica', 'Fullback', 'Regatas'),
  ('Pedro', 'Rossi', 'Ala', 'Regatas'),
  ('Felipe', 'Rugolo', 'Fullback', 'Regatas'),
  ('Santiago', 'Ruiz', 'Ala', 'Regatas'),
  ('Felipe', 'Ryan', 'Segunda Línea', 'Regatas'),
  ('Pedro', 'Sánchez', 'Octavo', 'Regatas'),
  ('Tomas', 'Sanguinetti', 'Segunda Línea', 'Regatas'),
  ('Valentin', 'Sanguinetti', 'Segunda Línea', 'Regatas'),
  ('Rafael', 'Santa Ana', 'Wing', 'Regatas'),
  ('Tomas', 'Santa Ana', 'Octavo', 'Regatas'),
  ('José', 'Sapia', 'Medio Scrum', 'Regatas'),
  ('Francisco', 'Sarlanga Pando', 'Ala', 'Regatas'),
  ('Mateo', 'Spenser Taiboat', 'Centro', 'Regatas'),
  ('Esteban', 'Sciandro', 'Pilar Derecho', 'Regatas'),
  ('Sebastián', 'Seco Pon', 'Centro', 'Regatas'),
  ('Bautista', 'Solveyra', 'Pilar Derecho', 'Regatas'),
  ('Juan', 'Sourrouille', 'Segunda Línea', 'Regatas'),
  ('Felipe', 'Terra', 'Wing', 'Regatas'),
  ('Felipe', 'Tommasini', 'Fullback', 'Regatas'),
  ('Manuel', 'Torrela', 'Segunda Línea', 'Regatas'),
  ('Diego', 'Torres Agüero', 'Pilar Izquierdo', 'Regatas'),
  ('Martin', 'Udaquiola', 'Centro', 'Regatas'),
  ('José', 'Vallega', 'Centro', 'Regatas'),
  ('Alan', 'Vater', 'Ala', 'Regatas'),
  ('Pedro', 'Vega', 'Ala', 'Regatas'),
  ('Facundo', 'Verdier', 'Fullback', 'Regatas'),
  ('Agustin Jose', 'Victory', 'Wing', 'Regatas'),
  ('Matías', 'Victory', 'Ala', 'Regatas'),
  ('Tomas', 'Vilches', 'Pilar Izquierdo', 'Regatas'),
  ('Franco', 'Yacubowski', 'Ala', 'Regatas'),
  ('Felipe', 'Zampella', 'Medio Scrum', 'Regatas'),
  ('Fermín', 'Zampella', 'Centro', 'Regatas'),
  ('Francisco', 'Zampella', 'Wing', 'Regatas'),
  ('Mateo', 'Zamudio', 'Wing', 'Regatas'),
  ('Marcos', 'Pereyra', 'Ala', 'Regatas'),
  ('Tomas', 'Batagglia', 'Fullback', 'Regatas'),
  ('Matias', 'Pirovano', 'Fullback', 'Regatas'),
  ('Benjamin', 'Prado', 'Wing', 'Regatas'),
  ('Manuel', 'Nozaglia', 'Octavo', 'Regatas'),
  ('Benito', 'Delfino', 'Wing', 'Regatas'),
  ('Juan Pablo', 'Norwin', 'Centro', 'Regatas'),
  ('Tomás', 'Elmiger', 'Octavo', 'Regatas'),
  ('Santiago', 'Findlay Wilson', 'Segunda Línea', 'Regatas'),
  ('Juan', 'Molina Campos', 'Wing', 'Regatas'),
  ('Benjamin', 'Laborda', 'Fullback', 'Regatas'),
  ('Felipe', 'Calvente', 'Wing', 'Regatas'),
  ('Rafael', 'Robles', 'Fullback', 'Regatas'),
  ('Rafael', 'Pan Peralta', 'Apertura', 'Regatas'),
  ('Tobias', 'Serpa', 'Centro', 'Regatas'),
  ('Santiago', 'Delatorre', 'Medio Scrum', 'Regatas'),
  ('Ramiro', 'Goncalvez', 'Fullback', 'Regatas'),
  ('Francisco', 'Falduti', 'Medio Scrum', 'Regatas'),
  ('Fabricio', 'Cebron', 'Pilar Izquierdo', 'Regatas'),
  ('Felipe', 'Pascual', 'Hooker', 'Regatas');
